# ==========================
# 1. Config Service
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  namespace: eks-msa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-service
        image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/sesac-jhj-msa/config-server:v1
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eks
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: eks-msa-project
spec:
  selector:
    app: config-server
  ports:
  - port: 8888
    targetPort: 8888
  type: ClusterIP

# ==========================
# 2. Eureka Server
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: eks-msa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/sesac-jhj-msa/eureka-server:v1
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eks
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: eks-msa-project
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
  type: ClusterIP

# ==========================
# 3. Api Gateway
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: eks-msa-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/sesac-jhj-msa/api-gateway:v1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eks
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: eks-msa-project
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer

# ==========================
# 4. User Service
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: eks-msa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/sesac-jhj-msa/user-service:v1
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eks
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: eks-msa-project
spec:
  selector:
    app: user-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP

# ==========================
# 5. Product Service
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: eks-msa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/sesac-jhj-msa/product-service:v1
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eks
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: eks-msa-project
spec:
  selector:
    app: product-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP

# ==========================
# 6. Order Service
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: eks-msa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/sesac-jhj-msa/order-service:v1
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eks
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: eks-msa-project
spec:
  selector:
    app: order-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP

# ==========================
# 7. Notification Service
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: eks-msa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/sesac-jhj-msa/notification-service:v1
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eks
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: eks-msa-project
spec:
  selector:
    app: notification-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP

# ==========================
# 8. Payment Service
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: eks-msa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/sesac-jhj-msa/payment-service:v1
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eks
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: eks-msa-project
spec:
  selector:
    app: payment-service
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP
