spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.sesac: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

  # zipkin 추가와 동시에 추가됨
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"

info:
  environment: "Development"
  debug: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, tracing, refresh
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

otel:
  exporter:
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans
  resource:
    attributes:
      service.name: ${spring.applicationi.name}

order:
  event:
    exchange: order.exchange    # 이벤트 이름
    queue:    # queue의 이름 정하기
      notification: order.notification.queue
      inventory: order.inventory.queue
    routing-key:  # 이벤트 발생시 어느 주소로 보내는가
      notification: order.notification
      inventory: order.inventory