server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3307/order_service_db


# User Service 호출에 대한 회복성 패턴
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        sliding-window-type: count-based    # count-based는 실패 판단을 횟수 기반으로 하겠다는 뜻
        sliding-window-size: 3
        minimum-number-of-calls: 3
        failure-rate-threshold: 50          # 50% 실패시 Circuit을 Open
        permitted-number-of-calls-in-half-open-state: 2   # half open 상태에서 테스트를 몇 번 할지